type TeamChampion = {
  name: string;
  tier: number;
  tags: string[];
};

const set18Champions: TeamChampion[] = [
  { name: "Akali", tier: 1, tags: ["inferno", "adaptor", "ravager"] },
  { name: "Camille", tier: 1, tags: ["coven", "ravager"] },
  { name: "Cinderling", tier: 1, tags: ["riftbeast", "hunter"] },
  { name: "Karma", tier: 1, tags: ["blossom", "spellweaver"] },
  { name: "Kobuko", tier: 1, tags: ["sprykin", "brawler"] },
  { name: "Leona", tier: 1, tags: ["solar", "defender"] },
  { name: "Ornn", tier: 1, tags: ["elderwood", "defender"] },
  { name: "Pebbles", tier: 1, tags: ["riftbeast", "invoker"] },
  { name: "Rakan", tier: 1, tags: ["fae", "juggernaut", "vanguard"] },
  { name: "Rek'Sai", tier: 1, tags: ["eldritch", "brawler"] },
  { name: "Varus", tier: 1, tags: ["inferno", "rapidfire"] },
  { name: "Veigar", tier: 1, tags: ["eldritch", "sprykin", "spellweaver"] },
  { name: "Xayah", tier: 1, tags: ["elderwood", "fae", "rapidfire"] },
  { name: "Yorick", tier: 1, tags: ["blossom", "juggernaut", "summoner"] },
  { name: "Alistar", tier: 2, tags: ["elderwood", "brawler"] },
  { name: "Caitlyn", tier: 2, tags: ["coven", "hunter"] },
  { name: "Elise", tier: 2, tags: ["coven", "vanguard"] },
  { name: "Gromp", tier: 2, tags: ["riftbeast", "adaptor"] },
  { name: "Kayle", tier: 2, tags: ["solar", "rapidfire"] },
  { name: "LeBlanc", tier: 2, tags: ["elderwood", "spellweaver"] },
  { name: "Murkwolf", tier: 2, tags: ["riftbeast", "ravager"] },
  { name: "Scuttlecrab", tier: 2, tags: ["riftbeast", "juggernaut"] },
  { name: "Sejuani", tier: 2, tags: ["solar", "juggernaut"] },
  { name: "Shen", tier: 2, tags: ["inferno", "defender"] },
  { name: "Teemo", tier: 2, tags: ["sprykin", "invoker"] },
  { name: "Warwick", tier: 2, tags: ["eldritch", "ravager"] },
  { name: "Yunara", tier: 2, tags: ["blossom", "executioner"] },
  { name: "Azir", tier: 3, tags: ["eldritch", "executioner", "summoner"] },
  { name: "Cassiopeia", tier: 3, tags: ["coven", "spellweaver"] },
  { name: "Diana", tier: 3, tags: ["lunar", "ravager", "vanguard"] },
  { name: "Fiddlesticks", tier: 3, tags: ["flora_fatalis", "defender", "spellweaver"] },
  { name: "Hecarim", tier: 3, tags: ["elderwood", "vanguard"] },
  { name: "Kha'Zix", tier: 3, tags: ["rival"] },
  { name: "Kog'Maw", tier: 3, tags: ["caustic", "invoker", "adaptor"] },
  { name: "Krug", tier: 3, tags: ["riftbeast", "brawler"] },
  { name: "Master Yi", tier: 3, tags: ["blossom", "adaptor"] },
  { name: "Rammus", tier: 3, tags: ["sprykin", "defender"] },
  { name: "Raptor", tier: 3, tags: ["riftbeast", "summoner", "rapidfire"] },
  { name: "Rengar", tier: 3, tags: ["rival"] },
  { name: "Tristana", tier: 3, tags: ["fae", "sprykin", "hunter"] },
  { name: "Vi", tier: 3, tags: ["primal", "juggernaut"] },
  { name: "Ahri", tier: 4, tags: ["blossom", "spellweaver"] },
  { name: "Amumu", tier: 4, tags: ["inferno", "juggernaut"] },
  { name: "Ancient Sentinel", tier: 4, tags: ["riftbeast", "vanguard", "invoker"] },
  { name: "Aphelios", tier: 4, tags: ["lunar", "rapidfire"] },
  { name: "Brambleback", tier: 4, tags: ["riftbeast", "ravager"] },
  { name: "Ezreal", tier: 4, tags: ["elderwood", "executioner"] },
  { name: "Lillia", tier: 4, tags: ["fae", "defender"] },
  { name: "Malphite", tier: 4, tags: ["eldritch", "monolith"] },
  { name: "Morgana", tier: 4, tags: ["coven", "invoker"] },
  { name: "Nidalee", tier: 4, tags: ["primal", "adaptor"] },
  { name: "Sett", tier: 4, tags: ["blossom", "brawler"] },
  { name: "Sivir", tier: 4, tags: ["primal", "hunter"] },
  { name: "Soraka", tier: 4, tags: ["flora_fatalis", "executioner"] },
  { name: "Zyra", tier: 4, tags: ["thornmaiden", "summoner"] },
  { name: "Alune", tier: 5, tags: ["attuned", "lunar", "spellweaver"] },
  { name: "Ashe", tier: 5, tags: ["blossom", "hunter"] },
  { name: "Draven", tier: 5, tags: ["bounty_seeker"] },
  { name: "The Elder Dragon", tier: 5, tags: ["riftbeast", "apex_predator"] },
  { name: "Gnar", tier: 5, tags: ["elderwood", "sprykin", "brawler"] },
  { name: "Ivern", tier: 5, tags: ["greenfather"] },
  { name: "Kennen", tier: 5, tags: ["inferno", "executioner"] },
  {
    name: "Lux",
    tier: 5,
    tags: ["avatar"],
  },
  { name: "Maokai", tier: 5, tags: ["old_growth", "juggernaut"] },
  { name: "Taric", tier: 5, tags: ["emerald_aspect", "vanguard"] },
];

export { set18Champions };
export type { TeamChampion };
